baseURL = "https://www.davidwang.com/"
languageCode = "en-us"
title = "David C Wang"
theme = "minimal"
disqusShortname = "" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "David C Wang"
    description = "Personal Blog"
    githubUsername = "" # leave empty string and explicitly provide org or user for repos
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["bash", "go", "python"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "https://github.com/dcwangmit01/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/dcwangmit01/"
    name = "linkedin"
    weight = 4
